name: 'Add D-5 Label'
description: 'add D-5 label on pull request'
inputs:
  github_token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: add label
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          async function addLabel() { 
            try{
              const prNumber = context.payload.pull_request.number;
              const { data: labels } = await github.rest.issues.listLabelsOnIssue({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber
              });

              if (labels.some(label => label.name.startsWith('D-'))) {
                console.log('D- label already exists.');
                return
              } 

              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: ['D-5'],
              });
              console.log('Label D-5 added.');
            } catch (error) {
              console.error('Error adding labels:', error);
            }
          };
          
          addLabel();